fileops:
    path:     /
    defaults: { _controller: "XarismaBundle:Fileops:index" }

admin_fileops_show:
    path:     /{id}/show
    defaults: { _controller: "XarismaBundle:Fileops:show" }

admin_fileops_newimport:
    path:     /newimport
    defaults: { _controller: "XarismaBundle:Fileops:newimport" }

admin_fileops_newexport:
    path:     /newexport
    defaults: { _controller: "XarismaBundle:Fileops:newexport" }

admin_fileops_create:
    path:     /create
    defaults: { _controller: "XarismaBundle:Fileops:create" }
    methods:  POST

admin_fileops_edit:
    path:     /{id}/edit
    defaults: { _controller: "XarismaBundle:Fileops:edit" }

admin_fileops_update:
    path:     /{id}/update
    defaults: { _controller: "XarismaBundle:Fileops:update" }
    methods:  [POST, PUT]

admin_fileops_delete:
    path:     /{id}/delete
    defaults: { _controller: "XarismaBundle:Fileops:delete" }
    methods:  [POST, DELETE]
