import:
    path:     /
    defaults: { _controller: "XarismaBundle:Import:index" }

import_show:
    path:     /{id}/show
    defaults: { _controller: "XarismaBundle:Import:show" }

import_new:
    path:     /new
    defaults: { _controller: "XarismaBundle:Import:new" }

import_create:
    path:     /create
    defaults: { _controller: "XarismaBundle:Import:create" }
    methods:  POST

import_edit:
    path:     /{id}/edit
    defaults: { _controller: "XarismaBundle:Import:edit" }

import_update:
    path:     /{id}/update
    defaults: { _controller: "XarismaBundle:Import:update" }
    methods:  [POST, PUT]

import_delete:
    path:     /{id}/delete
    defaults: { _controller: "XarismaBundle:Import:delete" }
    methods:  [POST, DELETE]
