admin_station:
    path:     /
    defaults: { _controller: "XarismaBundle:Station:index" }

admin_station_show:
    path:     /{id}/show
    defaults: { _controller: "XarismaBundle:Station:show" }

admin_station_new:
    path:     /new
    defaults: { _controller: "XarismaBundle:Station:new" }

admin_station_create:
    path:     /create
    defaults: { _controller: "XarismaBundle:Station:create" }
    methods:  POST

admin_station_edit:
    path:     /{id}/edit
    defaults: { _controller: "XarismaBundle:Station:edit" }

admin_station_update:
    path:     /{id}/update
    defaults: { _controller: "XarismaBundle:Station:update" }
    methods:  [POST, PUT]

admin_station_delete:
    path:     /{id}/delete
    defaults: { _controller: "XarismaBundle:Station:delete" }
    methods:  [POST, DELETE]
