XarismaBundle\Entity\Custorder:
    type: entity
    table: custorder
    indexes:
        IDX_196FD7DF9395C3F3:
            columns:
                - customer_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        ordernumber:
            type: string
            nullable: false
            length: 8
            fixed: false
            comment: ''
            column: orderNumber
        orderdate:
            type: datetime
            nullable: true
            comment: ''
        orderstatus:
            type: string
            nullable: true
            length: 100
            fixed: false
            comment: ''
            column: orderStatus
        notes:
            type: string
            nullable: true
            length: 3000
            fixed: false
            comment: ''
        updateby:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: updateBy
        datecreated:
            type: datetime
            nullable: true
            comment: ''
            column: dateCreated
        dateupdated:
            type: datetime
            nullable: true
            comment: ''
            column: dateUpdated
        deleted:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            column: Deleted
    manyToOne:
        customer:
            targetEntity: Customer
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                customer_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
