XarismaBundle\Entity\Dictionary:
    type: entity
    table: dictionary
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        class:
            type: string
            nullable: false
            length: 15
            fixed: false
            comment: ''
        term:
            type: string
            nullable: false
            length: 15
            fixed: false
            comment: ''
        definition:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
        datecreated:
            type: datetime
            nullable: true
            comment: ''
            default: CURRENT_TIMESTAMP
            column: dateCreated
        dateupdated:
            type: datetime
            nullable: true
            comment: ''
            column: dateUpdated
        deleted:
            type: integer
            nullable: false
            unsigned: false
            comment: 'Soft Delete. True= deleted'
            default: '0'
            column: Deleted
    lifecycleCallbacks: {  }
